version: "3.8"
name: SportBoard-container

services:
    postgres:
        image: postgres:13
        container_name: kong-database
        restart: always
        environment:
            POSTGRES_USER: kong
            POSTGRES_DB: kong
            POSTGRES_PASSWORD: kong
        ports:
            - "5432:5432"
        networks:
            - sportboard-network
        # Asegúrate de que PostgreSQL esté configurado para aceptar conexiones externas
        # Puedes agregar una configuración adicional en el archivo postgresql.conf si es necesario

    kong-migrations:
        image: kong:3.4
        container_name: kong-migrations
        restart: "no"
        depends_on:
            - postgres
        environment:
            KONG_DATABASE: postgres
            KONG_PG_HOST: postgres
            KONG_PG_USER: kong
            KONG_PG_PASSWORD: kong
        command: kong migrations bootstrap
        networks:
            - sportboard-network

    kong:
        image: kong:3.4
        container_name: kong
        restart: always # reiniciar siempre
        depends_on:
            - kong-migrations
        environment:
            KONG_DATABASE: postgres # base de datos
            KONG_PG_HOST: postgres  # host de la base de datos
            KONG_PG_USER: kong    # usuario de la base de datos
            KONG_PG_PASSWORD: kong    # contraseña de la base de datos
            KONG_PROXY_ACCESS_LOG: /dev/stdout # logs de acceso
            KONG_ADMIN_ACCESS_LOG: /dev/stdout # logs de acceso
            KONG_PROXY_ERROR_LOG: /dev/stderr   # logs de errores
            KONG_ADMIN_ERROR_LOG: /dev/stderr  # logs de errores
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl # puerto de administración
            KONG_ADMIN_GUI_URL: http://localhost:8002 # url de la interfaz de administración
        ports:
            - "8000:8000"
            - "8443:8443"
            - "8001:8001"
            - "8444:8444"
            - "8002:8002"
        volumes:
            - ./kong.yml:/kong.yml
        command: >
            sh -c "
            kong config db_import /kong.yml &&
            kong start
            "
        networks:
            - sportboard-network

networks:
    sportboard-network:
        external: true
