_format_version: "2.1"
_transform: true

services:
  - name: sportboard-backend
    url: http://ms4-estadisticas:3000
    routes:
      - name: teams-route
        paths:
          - /api/estadisticas/teams
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: matches-route-estadisticas
        paths:
          - /api/estadisticas/matches
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: competition-route
        paths:
          - /api/estadisticas/competition
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: upcoming-matches-route
        paths:
          - /api/estadisticas/upcomingMatches
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: leaderboards-route
        paths:
          - /api/estadisticas/leaderboards
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: players-route
        paths:
          - /api/estadisticas/players
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: generate-pdf-route
        paths:
          - /api/estadisticas/generate-teams-pdf
        strip_path: false
        methods:
          - POST
      - name: download-pdf-route
        paths:
          - /api/estadisticas/download-pdf
        strip_path: false
        methods:
          - GET
          - OPTIONS
      - name: test-route
        paths:
          - /api/estadisticas/test
        strip_path: false
        methods:
          - GET
          - OPTIONS
    plugins:
      - name: jwt
        config:
          claims_to_verify:
            - exp
          secret_is_base64: false
          run_on_preflight: true
          header_names:
            - authorization

  - name: groups-service
    url: http://catalogs:5241/api/groups
    routes:
      - name: groups-route
        paths:
          - /catalog/groups

  - name: catalogs-service
    url: http://catalogs:5241/api/catalogs
    routes:
      - name: catalogs-route
        paths:
          - /catalog/catalogs

  - name: real-time-service
    url: http://ms3-real-time:5001/api
    routes:
      - name: matches-route-realtime
        paths:
          - /api/partidos
      - name: events-route
        paths:
          - /api/eventos

  - name: ms2-competencies
    url: http://ms2-competencies:8003
    routes:
      - name: ms2-competencies-route
        paths:
          - /api
        strip_path: false

  - name: static-files
    url: http://ms2-competencies:8003
    routes:
      - name: static-files-route
        paths:
          - /static/
        strip_path: false

  - name: media-files
    url: http://ms2-competencies:8003
    routes:
      - name: media-files-route
        paths:
          - /media
        strip_path: false
        preserve_host: false

        
  - name: ms1-usermanagement
    url: http://ms1-usermanagement:8004
    routes:
      - name: ms1-usermanagement-route
        paths:
          - /ms1/
        strip_path: false

consumers:
  - username: sportboard-consumer
    jwt_secrets:
      - key: sportboard-statistics
        secret: "1234"
        algorithm: HS256

plugins:
  - name: cors
    config:
      origins:
        - http://localhost:4200
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - HEAD
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - Origin
        - X-Requested-With
      exposed_headers:
        - X-Auth-Token
      credentials: true
      max_age: 3600
      preflight_continue: false

